name: Linter action to check PEP8 rules

on:
  push:
    branches-ignore:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4.4.0
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Flake8 run
      run: |
        pip install flake8
        flake8 --max-line-length 120
    
